### ISSUE TITLE
Discussione del motivo per cui l'analisi delle ampiezze non porta

### ISSUE THREAD

**Issue by TheCodeEater** [TheCodeEater/lab_circuiti_relazione#12]
Nel branch analysis_amplitude ho fatto dele supposizioni sul perché il fit all'ampiezza non porta. Tralasciando strafalcioni vari perché ho sonno, ti sembra sensato ciò che ho scritto?

**Comment by Pe13** [comment]
Sì in generale direi che abbia senso, citerei magari il grafico del $V_{in}$, idealmente con un confronto con quello "corretto" con le capacità parassite, dicendo che qualitativamente ci sembra una strada percorribile ma che le formule fanno schifo e che dovremmo riprendere i dati consci di questo fenomeno. Tutto ciò per aggiungere qualcosa al
>Si può supporre che vi siano effetti reali che traslano sistematicamente il cross, i quali non sono tenuti in considerazione dal modello teorico
