### ISSUE TITLE
Frase poco chiara nell'introduzione

### ISSUE THREAD

**Issue by Pe13** [TheCodeEater/lab_circuiti_relazione#2]
Non capisco cosa vuoi dire con "L'attenuazione tuttavia non è nettamente definita nell'intorno di un
valore di frequenza dipendente dalle caratteristiche del circuito." ?
https://github.com/TheCodeEater/lab_circuiti_relazione/blob/cb395b91ce72e727b24e70e4d7caf28768dfe9b2/Sections/1-Introduzione.tex#L14-L17

**Comment by TheCodeEater** [comment]
No effettivamente vale per tutti i filtri. Ho riscritto quella parte cercando di eliminare i termini bassa e alta, visto che come diceva la Mauri non sono rigorose se solo qualitative. Mi sembra che ci siano un po' di ripetizioni nella parola frequenza
