### ISSUE TITLE
Struttura di apparato sperimentale

### ISSUE THREAD

**Issue by TheCodeEater** [TheCodeEater/lab_circuiti_relazione#3]
Dal momento che lo schema del crossover lo abbiamo già messo nell'introduzione, qui potremmo mettere una foto dell'apparato sperimentale (proprio la breadboard elvis, anche se non so quanto si capisca bene nel grovliglio di cavi).

Poi pensavo di elencare i valori misurati delle resistenze condensatore induttanza

**Comment by TheCodeEater** [comment]
Quoto. In ogni caso assieme alla pipeline metterei anche lo schema del circuito, dato che nella relazione esempio sul virtuale di anno scorso la hanno messa li.

**Comment by Pe13** [comment]
Ma non ha molto più senso mettere lo schema del circuito dove descrivi il circuito? (Mando una mail alla prof?)

**Comment by Pe13** [comment]
(l'ho mandata chiedendo se metterla nell' introduzione fosse contro il template)

**Comment by Pe13** [comment]
La prof ha detto che va bene
