### ISSUE TITLE
Correzione errore sistematico fase

### ISSUE THREAD

**Issue by TheCodeEater** [TheCodeEater/lab_circuiti_relazione#6]
Per correggere l'errore sistematico nella fase ho utilizzato il settle time delle specifiche di elvis (forse perché ho scritto il programma prima che lo misurassimo). Usando il settle time vero i valori di frequenza però non risultano compatibili e inoltre mi è stato fatto notare da Tommaso Carota che vi è anche un altro ritardo nell'acquisizione tra il trigger e l'avvio della conversione ADC. 

Mi viene da pensare che il settle time che abbiamo misurato includa anche questa porzione dell'errore. Tuttavia, se assumiamo che questa sia in media la stessa su entrambi i canali, non influisce sulla fase relativa. Per cui, correggere con il nostro settle time potrebbe portare ad effetti indesiderati

**Comment by Pe13** [comment]
> vi è anche un altro ritardo nell'acquisizione tra il trigger e l'avvio della conversione ADC.
Ma il delay tra trigger e ADC non è solo sulla prima misura in assoluto?
